### ISSUE TITLE
Queue feature let's you send 500+ messages at once

### ISSUE THREAD

**Issue by mac-cain13** [miguel250/PostmarkBundle#20]
The new queue method is awesome, but Postmark will only accept up to 500 messages at once. As far as I can see the bundle doesn't check for this limitation, so it's possible to queue more then 500 messages. I think it would be great if it would automatically flush when you queue message 501 or throw an exception so you can handle it yourself.

Right now it fails silently and I think that's not what any of us wants it to do.

**Comment by miguel250** [comment]
Right now it is not silently failing since postmark is returning an error code fcae3a0d4b342dcbbb104300e4a1a84f4f1b50bf. I dont think that automatically flushing when the queue gets to a 500 email is the way to go. Maybe adding a method that return the number of email in the queue and then the developer can choose to flush the emails or not. 

@ruudk what do you think?

**Comment by mac-cain13** [comment]
Agreed that an auto flush could lead to unexpected behavior. Espacially when you're queueing messages and later decide to not send them.

I think that a method returning the queue length would be nice and I would like an exception when queueing message 501 so I know immediately that the queue is full and can take action.

**Comment by ruudk** [comment]
Well, I've started working on my own implementation of a PostmarkBundle because I wanted support for delayed sending (via PHP-Resque jobs) and Twig template support.

But I've fixed it this way: https://github.com/ruudk/PostmarkBundle/blob/master/Postmark/Transport.php#L65

As you can see, I have a separate send() method that just checks how big the queue is and then sends them in chunks of 500 messages max.

**Comment by mac-cain13** [comment]
Sending in chunks of 500, why didn't I think of that. Way to go! :)

**Comment by miguel250** [comment]
Yeah it is. @mac-cain13 can you open a pull request with this changes?
